# Generated by Django 5.2.9 on 2025-12-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatarURL',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg', max_length=255, verbose_name='Profile picture'),
        ),
    ]
